apiVersion: v2
name: cert-manager
description: deploy cert-manager
type: application
version: 0.2.0

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.13.2
